# Generated by Django 5.0.6 on 2024-07-29 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_visitorsubjectcourse_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("soutien_scolaire", "Soutien scolaire"),
                            ("education_superieur", "Éducation supérieur"),
                            ("formation_pro", "Formation professionnelle"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("contact_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("auth_key", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="visitor",
            name="institution_user_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visitors",
                to="accounts.institution",
            ),
        ),
    ]
