# Generated by Django 5.0.7 on 2024-08-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_teacher_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="sso_url",
            field=models.URLField(default="selectionner", max_length=255),
            preserve_default=False,
        ),
    ]
