# Generated by Django 5.0.7 on 2024-08-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_institution_options_institution_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="auth_key",
            field=models.CharField(
                blank=True, max_length=255, unique=True, verbose_name="Clé d'API"
            ),
        ),
    ]
