# Generated by Django 5.0.7 on 2024-08-19 21:19

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_institution_auth_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="logo",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="institution_logos/",
            ),
        ),
    ]
