# Generated by Django 5.0.7 on 2024-08-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_alter_institution_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="logo",
            field=models.FileField(
                blank=True,
                null=True,
                storage="monFocus.storage_backends.MediaStorage",
                upload_to="institution_logos/",
            ),
        ),
    ]
