# Generated by Django 5.0.7 on 2024-08-23 18:26

import accounts.models
import monFocus.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_alter_institution_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="logo",
            field=models.FileField(
                blank=True,
                null=True,
                storage=monFocus.storage_backends.MediaStorage(),
                upload_to=accounts.models.institution_logo_path,
            ),
        ),
    ]
