# Generated by Django 5.0.6 on 2024-07-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monEspace", "0010_hourdeclaration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hourdeclaration",
            name="duration",
            field=models.DurationField(),
        ),
    ]
