# Generated by Django 5.0.7 on 2024-08-01 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monEspace", "0011_alter_hourdeclaration_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="embedding",
        ),
    ]
