# Generated by Django 5.0.7 on 2024-10-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monEspace", "0014_homework_homeworkfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="is_task_session",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="HourDeclaration",
        ),
    ]
